INSERT INTO Words (word, hint) VALUES
('Gato', 'Animal doméstico que mia'),
('Cachorro', 'Animal doméstico que late'),
('Maçã', 'Fruta vermelha ou verde'),
('Carro', 'Veículo motorizado'),
('Livro', 'Objeto para leitura'),
('Computador', 'Dispositivo eletrônico para processamento de dados'),
('Celular', 'Dispositivo de comunicação portátil'),
('Cachoeira', 'Queda de água em um rio'),
('Montanha', 'Grande elevação natural da superfície terrestre'),
('Luz', 'Fonte de iluminação'),
('Sol', 'Estrela central do nosso sistema solar'),
('Lua', 'Satélite natural da Terra'),
('Estrela', 'Corpo celeste que brilha no céu'),
('Planeta', 'Corpo celeste que orbita uma estrela'),
('Água', 'Substância essencial para a vida'),
('Terra', 'Planeta onde vivemos'),
('Fogo', 'Combustão que libera calor e luz'),
('Ar', 'Mistura de gases que compõe a atmosfera terrestre'),
('Nuvem', 'Aglomeração de gotas de água ou cristais de gelo no céu'),
('Chuva', 'Precipitação de gotas de água'),
('Neve', 'Precipitação de cristais de gelo'),
('Vento', 'Movimento do ar'),
('Relâmpago', 'Descarga elétrica na atmosfera'),
('Trovão', 'Som produzido pelo relâmpago'),
('Mar', 'Grande massa de água salgada'),
('Oceano', 'Maior massa de água salgada do planeta'),
('Rio', 'Curso de água natural'),
('Lago', 'Grande massa de água doce'),
('Floresta', 'Grande área coberta de árvores'),
('Deserto', 'Área com pouca precipitação e vegetação escassa'),
('Vulcão', 'Abertura na crosta terrestre que emite lava, cinzas e gases'),
('Terremoto', 'Tremor na crosta terrestre'),
('Tempestade', 'Fenômeno meteorológico com chuva, vento e trovões'),
('Ciclone', 'Sistema de ventos fortes em forma de espiral'),
('Tsunami', 'Onda gigante causada por terremoto ou erupção vulcânica'),
('Furacão', 'Ciclone tropical com ventos muito fortes'),
('Tornado', 'Coluna de ar giratória e destrutiva'),
('Aurora', 'Fenômeno luminoso no céu polar'),
('Galáxia', 'Grande aglomerado de estrelas, planetas e matéria escura'),
('Universo', 'Conjunto de tudo o que existe'),
('Cosmos', 'Outro termo para universo'),
('Gravidade', 'Força que atrai os corpos para o centro da Terra'),
('Órbita', 'Caminho que um corpo celeste percorre ao redor de outro'),
('Satélite', 'Corpo que orbita um planeta'),
('Cometa', 'Corpo celeste com núcleo de gelo e poeira'),
('Asteroide', 'Corpo rochoso que orbita o Sol'),
('Meteoro', 'Fenômeno luminoso causado pela entrada de um meteoroide na atmosfera terrestre'),
('Meteoroide', 'Pequeno corpo rochoso no espaço'),
('Meteorito', 'Fragmento de meteoroide que atinge a superfície da Terra');